pageinfo = [[1611581005,0,0,0,null],
	[1611581006,0,0,0,null],
	[1611581006,0,0,0,null],
	[1611581006,0,0,0,null],
	[1611581007,0,0,0,null],
	[1611581007,0,0,0,null],
	[1611581005,0,0,0,null],
	[1611581007,0,0,0,null],
	[1611581005,0,0,0,null],
	[1611581007,0,0,0,null],
	[1611581005,0,0,0,null],
	[1611581005,0,0,0,null],
	[1611581005,0,0,0,null],
	[1611581005,0,0,0,null],
	[1611581006,0,0,0,null],
	[1611581007,0,0,0,null],
	[1611581007,0,0,0,null],
	[1611581007,0,0,0,null],
	[1611581006,0,0,0,null],
	[1611581006,0,0,0,null],
	[1611581005,0,0,0,null],
	[1611581005,0,0,0,null],
	[1611581007,0,0,0,null],
	[1611581005,0,0,0,null],
	[1611581006,0,0,0,null],
	[1611581007,0,0,0,null],
	[1611581007,0,0,0,null],
	[1611581007,0,0,0,null],
	[1611581005,0,0,0,null],
	[1611581006,0,0,0,null],
	[1611581007,0,0,0,null],
	[1611581006,0,0,0,null],
	[1611581006,0,0,0,null],
	[1611581007,0,0,0,null],
	[1611581005,0,0,0,null],
	[1611581006,0,0,0,null],
	[1611581006,0,0,0,null],
	[1611581007,0,0,0,null],
	[1611581007,0,0,0,null],
	[1611581006,0,0,0,null],
	[1611581006,0,0,0,null],
	[1611581005,0,0,0,null],
	[1611581006,0,0,0,null],
	[1611581007,0,0,0,null],
	[1611581005,0,0,0,null]];
pagedata = [ ["./dmdw_4_0-manifold_definitions.html","4.0 manifold_definitions","Part of the global properties are the manifolds. See the example below from the cambridge Gis dataset (with :de_de language)  &#60;manifold_de...","./images/zoomimage.jpg"],
["./dmdw_categories--collections.html","Categories &#38; Collections","This section contains the data for collections and fields.","./images/zoomimage.jpg"],
["./dmdw_category.html","5 category","This is information to group the collection data. The categories are derived from the ACE, which name should be supplied to the DMDW.","./images/zoomimage.jpg"],
["./dmdw_collection.html","5.1 collection","Collections are within a category.  &#60;collection     name=\"ws_casing\"     external_name=\"Casing\" &#38;n...","./images/zoomimage.jpg"],
["./dmdw_collectionlist.html","Collection List Page","This page contains a list of all collections. When descriptions are provided (see Adding Descriptions) this is shown here as well as in the collec...","./images/zoomimage.jpg"],
["./dmdw_collection_page.html","Collection Pages","Example screenshot","./images/zoomimage.jpg"],
["./dmdw_common_fields.html","4.2 common_fields","When there are fields in more than one collection with essentially the same information, a list of field descriptions can be defined in the sectio...","./images/zoomimage.jpg"],
["./dmdw_css.html","CSS","Four different CSS stylesheet files are used in the pages:","./images/zoomimage.jpg"],
["./dmdw_customization.html","Customization","Customizations can be done on several levels: Skip tables Tables can be omitted from the export by redefining and/or subclassing the method dd_col...","./images/zoomimage.jpg"],
["./dmdw_custom_xsl.html","Custom.xsl","The next xsl:templates are used to provide text for every major chapter.  They should not be removed, but left empty if wanted. As they are t...","./images/zoomimage.jpg"],
["./dmdw_datamodel_history.html","Meta Data - Datamodel History","This section contains selected or all datamodel history records.","./images/zoomimage.jpg"],
["./dmdw_datamodel_info.html","Meta Data - datamodel_info","This section contains information on the version, dataset, ace used and the selected datamodel product name and datamodel module name.","./images/zoomimage.jpg"],
["./dmdw_datamodel_version.html","Datamodel Version","The product uses the the current_dd_version of a dataset in the HTML output filenames. This makes sure that not (by accident) data from different ...","./images/zoomimage.jpg"],
["./dmdw_default_topology_rules.html","4.1 default_topology_rules","This section is part of the global_properties section and lists the default topology rules for every manifold in the dataset.","./images/zoomimage.jpg"],
["./dmdw_enumerators.html","enumerators","The section enumerators contains a full list of all the enumerators defined in the dataset.","./images/zoomimage.jpg"],
["./dmdw_enumerator_page.html","Static Enumerators Page","The table has a style class &#39;Used&#39; or &#39;NotUsed&#39;, which enables visualisation, for example by adding the following style definition:","./images/zoomimage.jpg"],
["./dmdw_example.html","Example","This page has links to an example of html output.  The DMDW xml file is created from the gis database of the Cambridge demonstration database...","./images/zoomimage.jpg"],
["./dmdw_features.html","Features","The FileSet2.xsl stylesheet contains some special features:","./images/zoomimage.jpg"],
["./dmdw_field.html","5.1.1 field","The field element contains the basic information of a field.","./images/zoomimage.jpg"],
["./dmdw_fileset2_xsl.html","FileSet2.xsl","The template FileSet2.xsl is designed to create multiple pages:","./images/zoomimage.jpg"],
["./dmdw_geometry_mappings.html","4.3 geometry_mappings","When a datamodel uses frequently the same map_discriminator_method, a list with a description can be added to the global_properties section. When ...","./images/zoomimage.jpg"],
["./dmdw_getting-started.html","Getting started","Take the following steps:  Common Get the software from the repository;  Exporting data model to XML: Start an open smallworld session c...","./images/zoomimage.jpg"],
["./dmdw_global-properties-page.html","Global Properties Page","When (as shown in the example) common fields are defined, these are listed here.","./images/zoomimage.jpg"],
["./dmdw_global_properties.html","Meta Data - Global Properties","The global properties section contains global DD data from the dataset and information that cannot be extracted from the datamodel, but might help...","./images/zoomimage.jpg"],
["./dmdw_help_text.html","Adding Descriptions","An important part of the Datamodel Documentation is about describing the meaning of objects and properties.","./images/zoomimage.jpg"],
["./dmdw_html-output.html","HTML","HTML output can be generated by XSL sheets.  The HTML that is created by FileSet2.xsl is an interactive document with links and filters. The ...","./images/zoomimage.jpg"],
["./dmdw_interactive-enumerators-page.html","Interactive Enumerators Page","Example screenshot","./images/zoomimage.jpg"],
["./dmdw_int_topology_page.html","Interactive Topology Page","Example screenshot","./images/zoomimage.jpg"],
["./dmdw_meta-data.html","Meta Data","These elements contain information about the version of the datamodel and software.","./images/zoomimage.jpg"],
["./dmdw_modules.html","Modules","The ds_doc_writer module contains the following resources (in resources/base):","./images/zoomimage.jpg"],
["./dmdw_pages.html","Pages","This page contains a Table of Contents with all the HTML pages that are created, except the pages that contain information about a collection. ","./images/zoomimage.jpg"],
["./dmdw_processor.html","XSLT Processing","For the XSLT it is recommended to use the Saxon processor for the translation. It is fast, reliable, and informative regarding any kind of error i...","./images/zoomimage.jpg"],
["./dmdw_smallworld.html","Magik","The Magik part of the DMDW is available in the module ds_doc_writer of the product datamodel_doc_writer.","./images/zoomimage.jpg"],
["./dmdw_softjoins_page.html","SoftJoins_Page","Example screenshot","./images/zoomimage.jpg"],
["./dmdw_software_version.html","Meta Data - Software Version","This section contains information on the major software products, including the DMDW itself when the xml is generated.","./images/zoomimage.jpg"],
["./dmdw_soft_joins.html","soft_joins","Soft joins are completely managed in Magik. Soft joins can hold equally important relationships as normal joins from the data dictionary. Therefor...","./images/zoomimage.jpg"],
["./dmdw_specials.html","Specials","A specialised (sub)class (of) dm_dataset_specials can be used to add descriptions and other information to the XML.","./images/zoomimage.jpg"],
["./dmdw_static_topology_page.html","Static Topology Page","Example screenshot","./images/zoomimage.jpg"],
["./dmdw_technical-details.html","Technical Details Page","This page describes properties of the html document, the xml document and various other information.","./images/zoomimage.jpg"],
["./dmdw_topology.html","topology","Topology information is separated into:  The default topology rules (see 4.1 default_topology_rules)  &#60;default_topology_rules&#62; &#38;nb...","./images/zoomimage.jpg"],
["./dmdw_writer-api.html","API","DMDW Writer The API for the sw:dm_xml_writer is as shown below:   DMDW Translator The class sw:dm_xml_transformer offers a way to perform the...","./images/zoomimage.jpg"],
["./dmdw_xml-content.html","XML Content","All data is contained in the top element &#60;datamodel&#62;.","./images/zoomimage.jpg"],
["./dmdw_xsl-transform.html","XSLT Stylesheets","DMDW contains the following xsl version 2.0 stylesheets to to transform the dmdw xml into html.","./images/zoomimage.jpg"],
["./dmdw_your-pages.html","Your pages","The following pages are referenced by the HTML that is generated by the FileSet2.xsl sheet. The help link is created in the named template \"f...","./images/zoomimage.jpg"],
["./index.html","Overview","The Data Model Document Writer product is based on the following principles:","./images/zoomimage.jpg"]];
