hmLoadTopic({
hmKeywords:"",
hmTitle:"Meta Data - Software Version",
hmDescription:"This section contains information on the major software products, including the DMDW itself when the xml is generated.",
hmPrevLink:"dmdw_datamodel_history.html",
hmNextLink:"dmdw_global_properties.html",
hmParentLink:"dmdw_meta-data.html",
hmBreadCrumbs:"<a href=\"dmdw_xml-content.html\">XML Content<\/a> &gt; <a href=\"dmdw_meta-data.html\">Meta Data<\/a>",
hmTitlePath:"XML Content > Meta Data > 3 software_version",
hmHeader:"",
hmBody:"<p class=\"p_Normal\">This section contains information on the major software products, including the DMDW itself when the xml is generated.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_CodeExample\"><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&lt;<\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #800000;\">software_version<\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&gt;<\/span><br \/>\n\r<span class=\"f_CodeExample\" style=\"font-weight: bold; color: #000000;\"> &nbsp; <\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&lt;<\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #800000;\">sw_core<\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&gt;<\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #000000;\">5.2.0.0<\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&lt;\/<\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #800000;\">sw_core<\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&gt;<\/span><br \/>\n\r<span class=\"f_CodeExample\" style=\"font-weight: bold; color: #000000;\"> &nbsp; <\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&lt;<\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #800000;\">dm_doc_writer<\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&gt;<\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #000000;\">5.2.0.1<\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&lt;\/<\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #800000;\">dm_doc_writer<\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&gt;<\/span><br \/>\n\r<span class=\"f_CodeExample\" style=\"font-weight: bold; color: #000000;\"> &nbsp; <\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&lt;<\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #800000;\">water_supply_core<\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&gt;<\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #000000;\">5.2.0.148<\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&lt;\/<\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #800000;\">water_supply_core<\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&gt;<\/span><br \/>\n\r<span class=\"f_CodeExample\" style=\"color: #0000ff;\">&lt;\/<\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #800000;\">software_version<\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&gt;<\/span><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">To include more software product versions, add them to the <span style=\"font-weight: bold;\">products_for_version<\/span> of the <span style=\"font-weight: bold;\">dataset_specials<\/span>.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
