hmLoadTopic({
hmKeywords:"",
hmTitle:"CSS",
hmDescription:"Four different CSS stylesheet files are used in the pages:",
hmPrevLink:"dmdw_features.html",
hmNextLink:"dmdw_svg-diagram.html",
hmParentLink:"dmdw_html-output.html",
hmBreadCrumbs:"<a href=\"dmdw_html-output.html\">HTML<\/a>",
hmTitlePath:"HTML > CSS",
hmHeader:"",
hmBody:"<p class=\"p_Normal\">Four different CSS stylesheet files are used in the pages:<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<div style=\"text-align: left; text-indent: 0; padding: 0 0 0 0; margin: 0 0 0 0;\"><table class=\"swDefaultHeader\" >\n\r<tr class=\"swDefaultHeader\">\n\r<td class=\"swDefaultHeader\" style=\"width:6.1875rem; background-color:#ECECF0;\"><p class=\"p_Normal\">Filename<\/p>\n\r<\/td>\n\r<td class=\"swDefaultHeader\" style=\"width:78.8750rem; background-color:#ECECF0;\"><p class=\"p_Normal\">Style classes<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr class=\"swDefaultHeader\">\n\r<td class=\"swDefaultHeader\" style=\"width:6.1875rem;\"><p class=\"p_Normal\"><span style=\"font-weight: bold;\">html.css<\/span><\/p>\n\r<\/td>\n\r<td class=\"swDefaultHeader\" style=\"width:78.8750rem;\"><p class=\"p_Normal\">Overall styling, like html, body, a, a:hover, a:active, a:focus, h1, h2, h3, h4, table, th, tr, td, p, ol, ul, li<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr class=\"swDefaultHeader\">\n\r<td class=\"swDefaultHeader\" style=\"width:6.1875rem;\"><p class=\"p_Normal\"><span style=\"font-weight: bold;\">layout.css<\/span><\/p>\n\r<\/td>\n\r<td class=\"swDefaultHeader\" style=\"width:78.8750rem;\"><p class=\"p_Normal\">Overall styling of layout<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr class=\"swDefaultHeader\">\n\r<td class=\"swDefaultHeader\" style=\"width:6.1875rem;\"><p class=\"p_Normal\"><span style=\"font-weight: bold;\">dm.css<\/span><\/p>\n\r<\/td>\n\r<td class=\"swDefaultHeader\" style=\"width:78.8750rem;\"><p class=\"p_Normal\">Data specific styling:<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\"><span style=\"text-decoration: underline;\">Links<\/span>: a.CollectionLink, a.EnumeratorLink, a.SoftJoin;<br \/>\n\r<span style=\"text-decoration: underline;\">Table<\/span>: Several subclassed table styles;<br \/>\n\r<span style=\"text-decoration: underline;\">Sections<\/span>: .overview, &nbsp;.collections, .enumerators, .topology, .name, .technical, .Info, .manifold, .join, .geometry, &nbsp;.logical etc.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr class=\"swDefaultHeader\">\n\r<td class=\"swDefaultHeader\" style=\"width:6.1875rem;\"><p class=\"p_Normal\"><span style=\"font-weight: bold;\">custom.css<\/span><\/p>\n\r<\/td>\n\r<td class=\"swDefaultHeader\" style=\"width:78.8750rem;\"><p class=\"p_Normal\">Custom styles for logo and background etc.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr class=\"swDefaultHeader\">\n\r<td class=\"swDefaultHeader\" style=\"width:6.1875rem;\"><p class=\"p_Normal\"><span style=\"font-weight: bold;\">svg.css<\/span><\/p>\n\r<\/td>\n\r<td class=\"swDefaultHeader\" style=\"width:78.8750rem;\"><p class=\"p_Normal\">Styles for the SVG Datamodel Graphics <\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
