hmLoadTopic({
hmKeywords:"",
hmTitle:"Static Enumerators Page",
hmDescription:"The table has a style class \'Used\' or \'NotUsed\', which enables visualisation, for example by adding the following style definition:",
hmPrevLink:"dmdw_collectionlist.html",
hmNextLink:"dmdw_interactive-enumerators-page.html",
hmParentLink:"dmdw_your-pages.html",
hmBreadCrumbs:"<a href=\"dmdw_your-pages.html\">Your pages<\/a>",
hmTitlePath:"Your pages > Static Enumerators Page",
hmHeader:"",
hmBody:"<p class=\"p_Normal\">The table has a style class \'<span style=\"font-weight: bold;\">Used<\/span>\' or \'<span style=\"font-weight: bold;\">NotUsed<\/span>\', which enables visualisation, for example by adding the following style definition:<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_CodeExample\"><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #8000ff;\">.NotUsed <\/span><span class=\"f_CodeExample\" style=\"color: #000000;\">{<\/span><br \/>\n\r<span class=\"f_CodeExample\" style=\"color: #000000;\"> &nbsp;  <\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #000000;\">border-top-width<\/span><span class=\"f_CodeExample\" style=\"color: #000000;\">: 5<\/span><span class=\"f_CodeExample\" style=\"color: #0080ff;\">px<\/span><span class=\"f_CodeExample\" style=\"color: #000000;\">;<\/span><br \/>\n\r<span class=\"f_CodeExample\" style=\"color: #000000;\"> &nbsp;  <\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #000000;\">border-top-color<\/span><span class=\"f_CodeExample\" style=\"color: #000000;\">: <\/span><span class=\"f_CodeExample\" style=\"color: #0080ff;\">red<\/span><span class=\"f_CodeExample\" style=\"color: #000000;\">;<\/span><br \/>\n\r<span class=\"f_CodeExample\" style=\"color: #000000;\">}<\/span><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\"><img alt=\"dmdw_clip0018\" style=\"margin:0;width:25.0000rem;height:13.9375rem;border:none\" src=\".\/images\/dmdw_clip0018.png\"\/><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Figure\"><span class=\"f_Figure\"><a id=\"TOGGLE0186A1_LINK\" class=\"dropdown-toggle\" href=\"javascript:void(0)\" data-type=\"dropdown\" data-state=\"0\">Example screenshot<\/a><\/span><\/p>\n\r<div id=\"TOGGLE0186A1\" class=\"dropdown-toggle-body\" style=\"text-align: left; text-indent: 0; padding: 0 0 0 0; margin: 0 0 0 0;display:none\"><table class=\"Figure\" >\n\r<tr class=\"Figure\">\n\r<td class=\"Figure\"><p class=\"p_Normal\"><img alt=\"dmdw_clip0010\" style=\"margin:0;width:78.8125rem;height:43.1250rem;border:none\" src=\".\/images\/dmdw_clip0010.png\"\/><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
