hmLoadTopic({
hmKeywords:"",
hmTitle:"Features",
hmDescription:"The FileSet2.xsl stylesheet contains some special features:",
hmPrevLink:"dmdw_html-output.html",
hmNextLink:"dmdw_css.html",
hmParentLink:"dmdw_html-output.html",
hmBreadCrumbs:"<a href=\"dmdw_html-output.html\">HTML<\/a>",
hmTitlePath:"HTML > Features",
hmHeader:"",
hmBody:"<p class=\"p_Normal\">The <span style=\"font-weight: bold;\">FileSet2.xsl<\/span> stylesheet contains some special features:<\/p>\n\r<p class=\"p_Heading2\"><span class=\"f_Heading2\">Selective&nbsp;viewing<\/span><\/p>\n\r<p class=\"p_Normal\">The html pages contains specific style references that can be used for selecting and or visualisation. <br \/>\n\rFor example, the name of a geometry is tagged with class geometry. All invisible fields have the class VisFalse and can be hidden or shown<\/p>\n\r<p class=\"p_Normal\"><a href=\".\/images\/dmdw_clip0002.png\"><img id=\"TOGGLE0186A1\" class=\"image-toggle\" alt=\"Click to see the example\" title=\"Click to see the example\" style=\"margin:0;width:29.6875rem;height:14.3750rem;border:none\" src=\".\/images\/dmdw_clip0002_zoom30.png\" data-type=\"picture\" data-state=\"0\" data-src0=\".\/images\/dmdw_clip0002_zoom30.png\" data-src1=\".\/images\/dmdw_clip0002.png\" data-title0=\"Click to see the example\" data-title1=\"Click to see the example\"\/><\/a><\/p>\n\r<p class=\"p_Heading2\"><span class=\"f_Heading2\">Filtering<\/span><\/p>\n\r<p class=\"p_Normal\">When the list of <span style=\"font-weight: bold;\">enumerators<\/span> or <span style=\"font-weight: bold;\">topology<\/span> rules exceeds 100 elements, the page is divided in a navigation and presentation section.<br \/>\n\rThe list can be filtered. Individual element can be selected and viewed individually.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Enumerators:<\/p>\n\r<p class=\"p_Normal\"><a href=\".\/images\/dmdw_clip0003.png\"><img id=\"TOGGLE0186A2\" class=\"image-toggle\" alt=\"Click to see an example\" title=\"Click to see an example\" style=\"margin:0;width:30.0000rem;height:14.3750rem;border:none\" src=\".\/images\/dmdw_clip0003_zoom30.png\" data-type=\"picture\" data-state=\"0\" data-src0=\".\/images\/dmdw_clip0003_zoom30.png\" data-src1=\".\/images\/dmdw_clip0003.png\" data-title0=\"Click to see an example\" data-title1=\"Click to see an example\"\/><\/a><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Explicit Topology rules:<\/p>\n\r<p class=\"p_Normal\"><a href=\".\/images\/dmdw_clip0005.png\"><img id=\"TOGGLE0186A3\" class=\"image-toggle\" alt=\"dmdw_clip0005_zoom30\" style=\"margin:0;width:35.1875rem;height:17.6250rem;border:none\" src=\".\/images\/dmdw_clip0005_zoom30.png\" data-type=\"picture\" data-state=\"0\" data-src0=\".\/images\/dmdw_clip0005_zoom30.png\" data-src1=\".\/images\/dmdw_clip0005.png\"\/><\/a><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
