hmLoadTopic({
hmKeywords:"",
hmTitle:"Overview",
hmDescription:"The Data Model Document Writer product is based on the following principles:",
hmPrevLink:"",
hmNextLink:"dmdw_release-notes.html",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Overview",
hmHeader:"",
hmBody:"<p class=\"p_Normal\">The <span style=\"font-weight: bold;\">D<\/span>ata<span style=\"font-weight: bold;\"> M<\/span>odel<span style=\"font-weight: bold;\"> D<\/span>ocument<span style=\"font-weight: bold;\"> W<\/span>riter<span style=\"font-weight: bold;\"> <\/span>product is based on the following principles:<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Use a smallworld dataset as input;<\/p><p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Get as much information from the datamodel straight into xml;<\/p><p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Use XSLT to create human readable output in html;<\/p><p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Use specialized css and create id attributes for reference.<\/p><p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\"><img alt=\"dmdw_clip0026\" style=\"margin:0;width:53.5000rem;height:18.0000rem;border:none\" src=\".\/images\/dmdw_clip0026.png\"\/><\/p>\n\r<p class=\"p_Notes\"><span class=\"f_Notes\">This software has no GUI.<\/span><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">The software can be found at <a href=\"https:\/\/github.com\/boogert-lab\/dmdw\" target=\"_blank\" class=\"weblink\">https:\/\/github.com\/boogert-lab\/dmdw<\/a><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
