pageinfo = [[1613390814,0,0,0,null],
	[1613390814,0,0,0,null],
	[1613390814,0,0,0,null],
	[1613390814,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390814,0,0,0,null],
	[1613390815,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390813,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390814,0,0,0,null],
	[1613390814,0,0,0,null],
	[1613390813,0,0,0,null],
	[1613390814,0,0,0,null],
	[1613390815,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390815,0,0,0,null],
	[1613390815,0,0,0,null],
	[1613390815,0,0,0,null],
	[1613390814,0,0,0,null],
	[1613390813,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390814,0,0,0,null],
	[1613390815,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390813,0,0,0,null],
	[1613390815,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390815,0,0,0,null],
	[1613390813,0,0,0,null],
	[1613390815,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390814,0,0,0,null],
	[1613390815,0,0,0,null],
	[1613390815,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390815,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613390815,0,0,0,null],
	[1613390815,0,0,0,null],
	[1613390815,0,0,0,null],
	[1613390813,0,0,0,null],
	[1613390815,0,0,0,null],
	[1613390816,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204972,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204972,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204972,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204972,0,0,0,null],
	[1613204972,0,0,0,null],
	[1613204972,0,0,0,null],
	[1613204972,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204972,0,0,0,null],
	[1613204972,0,0,0,null],
	[1613204972,0,0,0,null],
	[1613204972,0,0,0,null],
	[1613204972,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204972,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204972,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204972,0,0,0,null],
	[1613204972,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null],
	[1613204971,0,0,0,null]];
pagedata = [ ["./dmdw_4_0-manifold_definitions.html","4.0 manifold_definitions","Part of the global properties are the manifolds. See the example below from the cambridge Gis dataset (with :de_de language)  &#60;manifold_de...","./images/zoomimage.jpg"],
["./dmdw_categories--collections.html","Categories &#38; Collections","This section contains the data for collections and fields.","./images/zoomimage.jpg"],
["./dmdw_category.html","5 category","This is information to group the collection data. The categories are derived from the ACE, which name should be supplied to the DMDW.","./images/zoomimage.jpg"],
["./dmdw_collection.html","5.1 collection","Collections are within a category.  &#60;collection     name=\"ws_casing\"     external_name=\"Casing\" &#38;n...","./images/zoomimage.jpg"],
["./dmdw_collectionlist.html","Collection List Page","This page contains a list of all collections. When descriptions are provided (see Adding Descriptions) this is shown here as well as in the collec...","./images/zoomimage.jpg"],
["./dmdw_collection_page.html","Collection Pages","Example screenshot","./images/zoomimage.jpg"],
["./dmdw_common_fields.html","4.2 common_fields","When there are fields in more than one collection with essentially the same information, a list of field descriptions can be defined in the sectio...","./images/zoomimage.jpg"],
["./dmdw_common_xsl.html","Common.xsl","The Common.xsl template contains the following templates:","./images/zoomimage.jpg"],
["./dmdw_css.html","CSS","Four different CSS stylesheet files are used in the pages:","./images/zoomimage.jpg"],
["./dmdw_customization.html","Customization","Customizations can be done on several levels: Skip tables Tables can be omitted from the export by redefining and/or subclassing the method dd_col...","./images/zoomimage.jpg"],
["./dmdw_custom_xsl.html","Custom.xsl","The next xsl:templates are used to provide text for every major chapter.  They should not be removed, but left empty if wanted. As they are t...","./images/zoomimage.jpg"],
["./dmdw_datamodel_history.html","Meta Data - Datamodel History","This section contains selected or all datamodel history records.","./images/zoomimage.jpg"],
["./dmdw_datamodel_info.html","Meta Data - datamodel_info","This section contains information on the version, dataset, ace used and the selected datamodel product name and datamodel module name.","./images/zoomimage.jpg"],
["./dmdw_datamodel_version.html","Datamodel Version","The product uses the the current_dd_version of a dataset in the HTML output filenames. This makes sure that not (by accident) data from different ...","./images/zoomimage.jpg"],
["./dmdw_default_topology_rules.html","4.1 default_topology_rules","This section is part of the global_properties section and lists the default topology rules for every manifold in the dataset.","./images/zoomimage.jpg"],
["./dmdw_enumerators.html","enumerators","The section enumerators contains a full list of all the enumerators defined in the dataset.","./images/zoomimage.jpg"],
["./dmdw_enumerator_page.html","Static Enumerators Page","Example screenshot   The table has a style class &#39;Used&#39; or &#39;NotUsed&#39;, which enables visualisation, for example by adding the following style ...","./images/zoomimage.jpg"],
["./dmdw_example.html","Example 1 (Older version)","This page has links to an example of html output.  The DMDW xml file is created from the gis database of the Cambridge demonstration database...","./images/zoomimage.jpg"],
["./dmdw_example_2.html","Example 2 (Latest version)","The following examples are created by the example procs export_camdb() and transform_camdb_xml() defined in the camdb_doc_writer/source/procs.magik","./images/zoomimage.jpg"],
["./dmdw_features.html","Features","The FileSet2.xsl stylesheet contains some special features:","./images/zoomimage.jpg"],
["./dmdw_field.html","5.1.1 field","The field element contains the basic information of a field.","./images/zoomimage.jpg"],
["./dmdw_fileset2_xsl.html","FileSet2.xsl","The template FileSet2.xsl is designed to create multiple pages:","./images/zoomimage.jpg"],
["./dmdw_fileset3_xsl.html","FileSet3.xsl","This template creates all pages without a dd_version prefix and and does not create the  &#39;redirection page&#39; as FileSet2.xsl.","./images/zoomimage.jpg"],
["./dmdw_geometry_mappings.html","4.3 geometry_mappings","When a datamodel uses frequently the same map_discriminator_method, a list with a description can be added to the global_properties section. When ...","./images/zoomimage.jpg"],
["./dmdw_getting-started.html","Getting started","Take the following steps:  Common Get the software from the repository;  Exporting data model to XML: Start an open smallworld session c...","./images/zoomimage.jpg"],
["./dmdw_global-properties-page.html","Global Properties Page","When (as shown in the example) common fields are defined, these are listed here.","./images/zoomimage.jpg"],
["./dmdw_global_properties.html","Meta Data - Global Properties","The global properties section contains global DD data from the dataset and information that cannot be extracted from the datamodel, but might help...","./images/zoomimage.jpg"],
["./dmdw_help_text.html","Adding Descriptions","An important part of the Datamodel Documentation is about describing the meaning of objects and properties.","./images/zoomimage.jpg"],
["./dmdw_html-output.html","HTML","HTML output can be generated from the XML by XSL sheets.","./images/zoomimage.jpg"],
["./dmdw_index-page.html","Index Page","When multiple exports are done, an index file can be created.","./images/zoomimage.jpg"],
["./dmdw_interactive-enumerators-page.html","Interactive Enumerators Page","Example screenshot","./images/zoomimage.jpg"],
["./dmdw_int_topology_page.html","Interactive Topology Page","Example screenshot","./images/zoomimage.jpg"],
["./dmdw_meta-data.html","Meta Data","These elements contain information about the version of the datamodel and software.","./images/zoomimage.jpg"],
["./dmdw_modules.html","Modules","The dm_doc_writer module contains the following resources (in resources/base):","./images/zoomimage.jpg"],
["./dmdw_pages.html","Pages","This page contains a Table of Contents with all the HTML pages that are created, except the pages that contain information about a collection. ","./images/zoomimage.jpg"],
["./dmdw_processor.html","XSLT Processing","For the XSLT it is recommended to use the Saxon processor for the translation. It is fast, reliable, and informative regarding any kind of error i...","./images/zoomimage.jpg"],
["./dmdw_release-notes.html","Release Notes","Release 2.0 Feb 2021 These are the major changes in DMDW. General Added the possibility to create and embed a diagram based on the graphics in the...","./images/zoomimage.jpg"],
["./dmdw_smallworld.html","Magik","The Magik part of the DMDW is available in the module dm_doc_writer of the product datamodel_doc_writer.","./images/zoomimage.jpg"],
["./dmdw_softjoins_page.html","SoftJoins_Page","Example screenshot","./images/zoomimage.jpg"],
["./dmdw_software_version.html","Meta Data - Software Version","This section contains information on the major software products, including the DMDW itself when the xml is generated.","./images/zoomimage.jpg"],
["./dmdw_soft_joins.html","soft_joins","Soft joins are completely managed in Magik. Soft joins can hold equally important relationships as normal joins from the data dictionary. Therefor...","./images/zoomimage.jpg"],
["./dmdw_specials.html","Specials","A specialised (sub)class (of) dm_dataset_specials can be used to add descriptions and other information to the XML.","./images/zoomimage.jpg"],
["./dmdw_static_topology_page.html","Static Topology Page","Example screenshot","./images/zoomimage.jpg"],
["./dmdw_svg-diagram.html","SVG Diagram","An easy way to visualize the datamodel objects and relationships is to make use of the existing graphics in the CASE database.","./images/zoomimage.jpg"],
["./dmdw_svgmap.html","Object-Relations Diagram","This page contains an inline SVG picture that displays the tables and relationships as they appear in the CASE database. It is optional.","./images/zoomimage.jpg"],
["./dmdw_technical-details.html","Technical Details Page","This page describes properties of the html document, the xml document and various other information.","./images/zoomimage.jpg"],
["./dmdw_topology.html","topology","Topology information is separated into:  The default topology rules (see 4.1 default_topology_rules)  &#60;default_topology_rules&#62; &#38;nb...","./images/zoomimage.jpg"],
["./dmdw_urns.html","URN&#39;s","Urns are added to:     1. Datamodel history records     2. Categories (ace record)     3. Collections     ...","./images/zoomimage.jpg"],
["./dmdw_writer-api.html","API","DMDW Writer The API for the sw:dm_xml_writer is as shown below:   DMDW Transformer The class sw:dm_xml_transformer offers a way to perform th...","./images/zoomimage.jpg"],
["./dmdw_xml-content.html","XML Content","All data is contained in the top element &#60;datamodel&#62;.","./images/zoomimage.jpg"],
["./dmdw_xsl-transform.html","XSLT Stylesheets","DMDW contains the following xsl version 2.0 stylesheets to to transform the dmdw xml into html.","./images/zoomimage.jpg"],
["./dmdw_your-pages.html","Your pages","The following pages are referenced by the HTML that is generated by the FileSet2.xsl sheet. The help link is created in the named template \"f...","./images/zoomimage.jpg"],
["./example_html/electricity.html","Electricity - Table of Contents","Datamodel information Electricity Table of Contents Graphic Representation Technical Details Global Properties Collections Enumerators (static) En...",""],
["./example_html/electricity_pages/electricity_busbar.html","Electricity - Collection Busbar","Datamodel information Electricity Busbar Technical details Mapped fields Invisible fields Busbar busbar Category: Not in ACE &#39;electricity&#39; Name In...",""],
["./example_html/electricity_pages/electricity_cable.html","Electricity - Collection Cable","Datamodel information Electricity Cable Technical details Mapped fields Invisible fields Cable cable Category: Electricity Network Name Internal n...",""],
["./example_html/electricity_pages/electricity_collections.html","Electricity - List of Collections","Datamodel information Electricity Collections by Category The descriptions of the collections are supplied seperately. Their origin is not the dat...",""],
["./example_html/electricity_pages/electricity_construction.html","Electricity - Collection Construction","Datamodel information Electricity Construction Technical details Mapped fields Invisible fields Construction construction Category: Drawing Name I...",""],
["./example_html/electricity_pages/electricity_customer.html","Electricity - Collection Customer","Datamodel information Electricity Customer Technical details Mapped fields Invisible fields Customer customer Category: Electricity Network Name I...",""],
["./example_html/electricity_pages/electricity_dimension.html","Electricity - Collection Dimension","Datamodel information Electricity Dimension Technical details Mapped fields Invisible fields Dimension dimension Category: Drawing Name Internal n...",""],
["./example_html/electricity_pages/electricity_dm_svg.html","Electricity - Map","Datamodel information Electricity DMDW Case Heterogeneous Relationships Case Relationships Case Objects Cable Transformer Drawing Substation Suppl...",""],
["./example_html/electricity_pages/electricity_drafting_areas.html","Electricity - Collection Drafting Areas","Datamodel information Electricity Drafting Areas Technical details Mapped fields Invisible fields Drafting Areas drafting_areas Category: Drawing ...",""],
["./example_html/electricity_pages/electricity_drafting_lines.html","Electricity - Collection Drafting Lines","Datamodel information Electricity Drafting Lines Technical details Mapped fields Invisible fields Drafting Lines drafting_lines Category: Drawing ...",""],
["./example_html/electricity_pages/electricity_drafting_points.html","Electricity - Collection Drafting Points","Datamodel information Electricity Drafting Points Technical details Mapped fields Invisible fields Drafting Points drafting_points Category: Drawi...",""],
["./example_html/electricity_pages/electricity_drafting_texts.html","Electricity - Collection Drafting Texts","Datamodel information Electricity Drafting Texts Technical details Mapped fields Invisible fields Drafting Texts drafting_texts Category: Drawing ...",""],
["./example_html/electricity_pages/electricity_drawing.html","Electricity - Collection Zeichnung","Datamodel information Electricity Zeichnung Technical details Mapped fields Invisible fields Zeichnung drawing Category: Not in ACE &#39;electricity&#39; ...",""],
["./example_html/electricity_pages/electricity_drawing_function.html","Electricity - Collection Drawing Function","Datamodel information Electricity Drawing Function Technical details Mapped fields Invisible fields Drawing Function drawing_function Category: No...",""],
["./example_html/electricity_pages/electricity_drawing_template.html","Electricity - Collection Drawing Template","Datamodel information Electricity Drawing Template Technical details Mapped fields Invisible fields Drawing Template drawing_template Category: No...",""],
["./example_html/electricity_pages/electricity_dxf_areas.html","Electricity - Collection DXF Areas","Datamodel information Electricity DXF Areas Technical details Mapped fields Invisible fields DXF Areas dxf_areas Category: Not in ACE &#39;electricity...",""],
["./example_html/electricity_pages/electricity_dxf_attribs.html","Electricity - Collection DXF Attributes","Datamodel information Electricity DXF Attributes Technical details Mapped fields Invisible fields DXF Attributes dxf_attribs Category: Not in ACE ...",""],
["./example_html/electricity_pages/electricity_dxf_block_area.html","Electricity - Collection DXF Block Area","Datamodel information Electricity DXF Block Area Technical details Mapped fields Invisible fields DXF Block Area dxf_block_area Category: Not in A...",""],
["./example_html/electricity_pages/electricity_dxf_block_dimension.html","Electricity - Collection DXF Block Dimension","Datamodel information Electricity DXF Block Dimension Technical details Mapped fields Invisible fields DXF Block Dimension dxf_block_dimension Cat...",""],
["./example_html/electricity_pages/electricity_dxf_block_insert.html","Electricity - Collection DXF Block Insert","Datamodel information Electricity DXF Block Insert Technical details Mapped fields Invisible fields DXF Block Insert dxf_block_insert Category: No...",""],
["./example_html/electricity_pages/electricity_dxf_block_line.html","Electricity - Collection DXF Block Line","Datamodel information Electricity DXF Block Line Technical details Mapped fields Invisible fields DXF Block Line dxf_block_line Category: Not in A...",""],
["./example_html/electricity_pages/electricity_dxf_block_point.html","Electricity - Collection DXF Block Point","Datamodel information Electricity DXF Block Point Technical details Mapped fields Invisible fields DXF Block Point dxf_block_point Category: Not i...",""],
["./example_html/electricity_pages/electricity_dxf_block_text.html","Electricity - Collection DXF Block Text","Datamodel information Electricity DXF Block Text Technical details Mapped fields Invisible fields DXF Block Text dxf_block_text Category: Not in A...",""],
["./example_html/electricity_pages/electricity_dxf_dimensions.html","Electricity - Collection DXF Dimensions","Datamodel information Electricity DXF Dimensions Technical details Mapped fields Invisible fields DXF Dimensions dxf_dimensions Category: Not in A...",""],
["./example_html/electricity_pages/electricity_dxf_inserts.html","Electricity - Collection DXF Inserts","Datamodel information Electricity DXF Inserts Technical details Mapped fields Invisible fields DXF Inserts dxf_inserts Category: Not in ACE &#39;elect...",""],
["./example_html/electricity_pages/electricity_dxf_lines.html","Electricity - Collection DXF Lines","Datamodel information Electricity DXF Lines Technical details Mapped fields Invisible fields DXF Lines dxf_lines Category: Not in ACE &#39;electricity...",""],
["./example_html/electricity_pages/electricity_dxf_load_history.html","Electricity - Collection DXF Load History","Datamodel information Electricity DXF Load History Technical details Mapped fields Invisible fields DXF Load History dxf_load_history Category: No...",""],
["./example_html/electricity_pages/electricity_dxf_points.html","Electricity - Collection DXF Points","Datamodel information Electricity DXF Points Technical details Mapped fields Invisible fields DXF Points dxf_points Category: Not in ACE &#39;electric...",""],
["./example_html/electricity_pages/electricity_dxf_texts.html","Electricity - Collection DXF Texts","Datamodel information Electricity DXF Texts Technical details Mapped fields Invisible fields DXF Texts dxf_texts Category: Not in ACE &#39;electricity...",""],
["./example_html/electricity_pages/electricity_enumerators.html","Electricity - List of Enumerators","Datamodel information Electricity Enumerators (interactive) Show all drawing_function_evaluation drawing_orientation drawing_scale dunits_descr st...",""],
["./example_html/electricity_pages/electricity_enumerators_static.html","Electricity - List of Enumerators","Datamodel information Electricity Enumerators (static) drawing_function_evaluation Type Domain Class Storage Class mapped 2 On Insert Pre-Redraw P...",""],
["./example_html/electricity_pages/electricity_function_areas.html","Electricity - Collection Function Areas","Datamodel information Electricity Function Areas Technical details Mapped fields Invisible fields Function Areas function_areas Category: Not in A...",""],
["./example_html/electricity_pages/electricity_function_geometry.html","Electricity - Collection Function Geometry","Datamodel information Electricity Function Geometry Technical details Mapped fields Invisible fields Function Geometry function_geometry Category:...",""],
["./example_html/electricity_pages/electricity_function_lines.html","Electricity - Collection Function Lines","Datamodel information Electricity Function Lines Technical details Mapped fields Invisible fields Function Lines function_lines Category: Not in A...",""],
["./example_html/electricity_pages/electricity_function_points.html","Electricity - Collection Function Points","Datamodel information Electricity Function Points Technical details Mapped fields Invisible fields Function Points function_points Category: Not i...",""],
["./example_html/electricity_pages/electricity_function_texts.html","Electricity - Collection Function Texts","Datamodel information Electricity Function Texts Technical details Mapped fields Invisible fields Function Texts function_texts Category: Not in A...",""],
["./example_html/electricity_pages/electricity_global_properties.html","Electricity - Global properties","Datamodel information Electricity Global Properties These properties are global to the datamodel. It includes the default topology interaction, co...",""],
["./example_html/electricity_pages/electricity_int!drawing_pl_of_interes.html","Electricity - Collection int!drawing_pl_of_interes","Datamodel information Electricity int!drawing_pl_of_interes Technical details Mapped fields Invisible fields int!drawing_pl_of_interes int!drawing...",""],
["./example_html/electricity_pages/electricity_int!supply_point_customer.html","Electricity - Collection int!supply_point_customer","Datamodel information Electricity int!supply_point_customer Technical details Mapped fields Invisible fields int!supply_point_customer int!supply_...",""],
["./example_html/electricity_pages/electricity_internal_cable.html","Electricity - Collection Internal Cable","Datamodel information Electricity Internal Cable Technical details Mapped fields Invisible fields Internal Cable internal_cable Category: Not in A...",""],
["./example_html/electricity_pages/electricity_joint.html","Electricity - Collection Joint","Datamodel information Electricity Joint Technical details Mapped fields Invisible fields Joint joint Category: Electricity Network Name Internal n...",""],
["./example_html/electricity_pages/electricity_substation.html","Electricity - Collection Substation","Datamodel information Electricity Substation Technical details Mapped fields Invisible fields Substation substation Category: Electricity Network ...",""],
["./example_html/electricity_pages/electricity_substation_internals.html","Electricity - Collection Substation Internals","Datamodel information Electricity Substation Internals Technical details Mapped fields Invisible fields Substation Internals substation_internals ...",""],
["./example_html/electricity_pages/electricity_substation_internals_link.html","Electricity - Collection Substation Internals Link","Datamodel information Electricity Substation Internals Link Technical details Mapped fields Invisible fields Substation Internals Link substation_...",""],
["./example_html/electricity_pages/electricity_supply_point.html","Electricity - Collection Supply Point","Datamodel information Electricity Supply Point Technical details Mapped fields Invisible fields Supply Point supply_point Category: Electricity Ne...",""],
["./example_html/electricity_pages/electricity_swif!info_flag.html","Electricity - Collection Information Flag","Datamodel information Electricity Information Flag Technical details Mapped fields Invisible fields Information Flag swif!info_flag Category: Not ...",""],
["./example_html/electricity_pages/electricity_swif!info_flag_to_object1.html","Electricity - Collection swif!info_flag_to_object1","Datamodel information Electricity swif!info_flag_to_object1 Technical details Mapped fields Invisible fields swif!info_flag_to_object1 swif!info_f...",""],
["./example_html/electricity_pages/electricity_swif!info_flag_to_object2.html","Electricity - Collection swif!info_flag_to_object2","Datamodel information Electricity swif!info_flag_to_object2 Technical details Mapped fields Invisible fields swif!info_flag_to_object2 swif!info_f...",""],
["./example_html/electricity_pages/electricity_swif!info_flag_to_object3.html","Electricity - Collection swif!info_flag_to_object3","Datamodel information Electricity swif!info_flag_to_object3 Technical details Mapped fields Invisible fields swif!info_flag_to_object3 swif!info_f...",""],
["./example_html/electricity_pages/electricity_switch.html","Electricity - Collection Switch","Datamodel information Electricity Switch Technical details Mapped fields Invisible fields Switch switch Category: Not in ACE &#39;electricity&#39; Name In...",""],
["./example_html/electricity_pages/electricity_sw_gis!drawing_function_param.html","Electricity - Collection sw_gis!drawing_function_param","Datamodel information Electricity sw_gis!drawing_function_param Technical details Mapped fields Invisible fields sw_gis!drawing_function_param sw_...",""],
["./example_html/electricity_pages/electricity_technical_details.html","Electricity - Technical details","Datamodel information Electricity Technical Details Document Information Document Generation Date 2021-02-12+01:00 XML Document Generation Date 20...",""],
["./example_html/electricity_pages/electricity_topology.html","Electricity - Topology Rules","Datamodel information Electricity Topology Rules (interactive) When you select a Table on the left side, the geometries are shown. Then select one...",""],
["./example_html/electricity_pages/electricity_topology_static.html","Electricity - Topology Rules","Datamodel information Electricity Topology Rules (static) Explicit Rules only Manifold [Electricity] Elektrizitätsnetz Busbar Location Dv Internal...",""],
["./example_html/electricity_pages/electricity_transformer.html","Electricity - Collection Transformer","Datamodel information Electricity Transformer Technical details Mapped fields Invisible fields Transformer transformer Category: Not in ACE &#39;elect...",""],
["./example_html/electricity_pages/electricity_viewport_mapping.html","Electricity - Collection Viewport Mapping","Datamodel information Electricity Viewport Mapping Technical details Mapped fields Invisible fields Viewport Mapping viewport_mapping Category: No...",""],
["./example_html/gis.html","Gis - Table of Contents","Datamodel information Gis Table of Contents Graphic Representation Technical Details Global Properties Collections Enumerators (static) Enumerator...",""],
["./example_html/gis_pages/gis_beer.html","Gis - Collection Bier","Datamodel information Gis Bier Technical details Mapped fields Invisible fields Bier beer Category: Not in ACE &#39;electricity&#39; Name Internal name Si...",""],
["./example_html/gis_pages/gis_brewery.html","Gis - Collection Brauerei","Datamodel information Gis Brauerei Technical details Mapped fields Invisible fields Brauerei brewery Category: Not in ACE &#39;electricity&#39; Name Inter...",""],
["./example_html/gis_pages/gis_cadastral_boundary.html","Gis - Collection Cadastral Boundary","Datamodel information Gis Cadastral Boundary Technical details Mapped fields Invisible fields Cadastral Boundary cadastral_boundary Category: Cada...",""],
["./example_html/gis_pages/gis_car_park.html","Gis - Collection Parkplatz","Datamodel information Gis Parkplatz Technical details Mapped fields Invisible fields Parkplatz car_park Category: Road Network Name Internal name ...",""],
["./example_html/gis_pages/gis_collections.html","Gis - List of Collections","Datamodel information Gis Collections by Category The descriptions of the collections are supplied seperately. Their origin is not the datamodel. ...",""],
["./example_html/gis_pages/gis_company.html","Gis - Collection Firma","Datamodel information Gis Firma Technical details Mapped fields Invisible fields Firma company Category: Non Topological Objects Name Internal nam...",""],
["./example_html/gis_pages/gis_construction.html","Gis - Collection Construction","Datamodel information Gis Construction Technical details Mapped fields Invisible fields Construction construction Category: Non Topological Object...",""],
["./example_html/gis_pages/gis_dimension.html","Gis - Collection Dimension","Datamodel information Gis Dimension Technical details Mapped fields Invisible fields Dimension dimension Category: Drafting Name Internal name Siz...",""],
["./example_html/gis_pages/gis_dm_svg.html","Gis - Map","Datamodel information Gis DMDW Case Heterogeneous Relationships Case Relationships Case Objects Car Park Road Catalogue Roundabout Office Office V...",""],
["./example_html/gis_pages/gis_drafting_areas.html","Gis - Collection Drafting Areas","Datamodel information Gis Drafting Areas Technical details Mapped fields Invisible fields Drafting Areas drafting_areas Category: Drafting Name In...",""],
["./example_html/gis_pages/gis_drafting_lines.html","Gis - Collection Drafting Lines","Datamodel information Gis Drafting Lines Technical details Mapped fields Invisible fields Drafting Lines drafting_lines Category: Drafting Name In...",""],
["./example_html/gis_pages/gis_drafting_points.html","Gis - Collection Drafting Points","Datamodel information Gis Drafting Points Technical details Mapped fields Invisible fields Drafting Points drafting_points Category: Drafting Name...",""],
["./example_html/gis_pages/gis_drafting_texts.html","Gis - Collection Drafting Texts","Datamodel information Gis Drafting Texts Technical details Mapped fields Invisible fields Drafting Texts drafting_texts Category: Drafting Name In...",""],
["./example_html/gis_pages/gis_drawing.html","Gis - Collection Zeichnung","Datamodel information Gis Zeichnung Technical details Mapped fields Invisible fields Zeichnung drawing Category: Not in ACE &#39;electricity&#39; Name Int...",""],
["./example_html/gis_pages/gis_drawing_function.html","Gis - Collection Drawing Function","Datamodel information Gis Drawing Function Technical details Mapped fields Invisible fields Drawing Function drawing_function Category: Not in ACE...",""],
["./example_html/gis_pages/gis_drawing_template.html","Gis - Collection Drawing Template","Datamodel information Gis Drawing Template Technical details Mapped fields Invisible fields Drawing Template drawing_template Category: Not in ACE...",""],
["./example_html/gis_pages/gis_dxf_areas.html","Gis - Collection DXF Areas","Datamodel information Gis DXF Areas Technical details Mapped fields Invisible fields DXF Areas dxf_areas Category: Not in ACE &#39;electricity&#39; Name I...",""],
["./example_html/gis_pages/gis_dxf_attribs.html","Gis - Collection DXF Attributes","Datamodel information Gis DXF Attributes Technical details Mapped fields Invisible fields DXF Attributes dxf_attribs Category: Not in ACE &#39;electri...",""],
["./example_html/gis_pages/gis_dxf_block_area.html","Gis - Collection DXF Block Area","Datamodel information Gis DXF Block Area Technical details Mapped fields Invisible fields DXF Block Area dxf_block_area Category: Not in ACE &#39;elec...",""],
["./example_html/gis_pages/gis_dxf_block_dimension.html","Gis - Collection DXF Block Dimension","Datamodel information Gis DXF Block Dimension Technical details Mapped fields Invisible fields DXF Block Dimension dxf_block_dimension Category: N...",""],
["./example_html/gis_pages/gis_dxf_block_insert.html","Gis - Collection DXF Block Insert","Datamodel information Gis DXF Block Insert Technical details Mapped fields Invisible fields DXF Block Insert dxf_block_insert Category: Not in ACE...",""],
["./example_html/gis_pages/gis_dxf_block_line.html","Gis - Collection DXF Block Line","Datamodel information Gis DXF Block Line Technical details Mapped fields Invisible fields DXF Block Line dxf_block_line Category: Not in ACE &#39;elec...",""],
["./example_html/gis_pages/gis_dxf_block_point.html","Gis - Collection DXF Block Point","Datamodel information Gis DXF Block Point Technical details Mapped fields Invisible fields DXF Block Point dxf_block_point Category: Not in ACE &#39;e...",""],
["./example_html/gis_pages/gis_dxf_block_text.html","Gis - Collection DXF Block Text","Datamodel information Gis DXF Block Text Technical details Mapped fields Invisible fields DXF Block Text dxf_block_text Category: Not in ACE &#39;elec...",""],
["./example_html/gis_pages/gis_dxf_dimensions.html","Gis - Collection DXF Dimensions","Datamodel information Gis DXF Dimensions Technical details Mapped fields Invisible fields DXF Dimensions dxf_dimensions Category: Not in ACE &#39;elec...",""],
["./example_html/gis_pages/gis_dxf_inserts.html","Gis - Collection DXF Inserts","Datamodel information Gis DXF Inserts Technical details Mapped fields Invisible fields DXF Inserts dxf_inserts Category: Not in ACE &#39;electricity&#39; ...",""],
["./example_html/gis_pages/gis_dxf_lines.html","Gis - Collection DXF Lines","Datamodel information Gis DXF Lines Technical details Mapped fields Invisible fields DXF Lines dxf_lines Category: Not in ACE &#39;electricity&#39; Name I...",""],
["./example_html/gis_pages/gis_dxf_load_history.html","Gis - Collection DXF Load History","Datamodel information Gis DXF Load History Technical details Mapped fields Invisible fields DXF Load History dxf_load_history Category: Not in ACE...",""],
["./example_html/gis_pages/gis_dxf_points.html","Gis - Collection DXF Points","Datamodel information Gis DXF Points Technical details Mapped fields Invisible fields DXF Points dxf_points Category: Not in ACE &#39;electricity&#39; Nam...",""],
["./example_html/gis_pages/gis_dxf_texts.html","Gis - Collection DXF Texts","Datamodel information Gis DXF Texts Technical details Mapped fields Invisible fields DXF Texts dxf_texts Category: Not in ACE &#39;electricity&#39; Name I...",""],
["./example_html/gis_pages/gis_enumerators.html","Gis - List of Enumerators","Datamodel information Gis Enumerators (interactive) Show all beer_type carriage_type cuisine drawing_function_evaluation drawing_orientation drawi...",""],
["./example_html/gis_pages/gis_enumerators_static.html","Gis - List of Enumerators","Datamodel information Gis Enumerators (static) beer_type Type Domain Class Storage Class simple Ale Stout Bitter Cider Lager Draught Fields using ...",""],
["./example_html/gis_pages/gis_footpath.html","Gis - Collection Fußweg","Datamodel information Gis Fußweg Technical details Mapped fields Invisible fields Fußweg footpath Category: Road Network Name Internal name Size K...",""],
["./example_html/gis_pages/gis_function_areas.html","Gis - Collection Function Areas","Datamodel information Gis Function Areas Technical details Mapped fields Invisible fields Function Areas function_areas Category: Not in ACE &#39;elec...",""],
["./example_html/gis_pages/gis_function_geometry.html","Gis - Collection Function Geometry","Datamodel information Gis Function Geometry Technical details Mapped fields Invisible fields Function Geometry function_geometry Category: Not in ...",""],
["./example_html/gis_pages/gis_function_lines.html","Gis - Collection Function Lines","Datamodel information Gis Function Lines Technical details Mapped fields Invisible fields Function Lines function_lines Category: Not in ACE &#39;elec...",""],
["./example_html/gis_pages/gis_function_points.html","Gis - Collection Function Points","Datamodel information Gis Function Points Technical details Mapped fields Invisible fields Function Points function_points Category: Not in ACE &#39;e...",""],
["./example_html/gis_pages/gis_function_texts.html","Gis - Collection Function Texts","Datamodel information Gis Function Texts Technical details Mapped fields Invisible fields Function Texts function_texts Category: Not in ACE &#39;elec...",""],
["./example_html/gis_pages/gis_global_properties.html","Gis - Global properties","Datamodel information Gis Global Properties These properties are global to the datamodel. It includes the default topology interaction, commonly u...",""],
["./example_html/gis_pages/gis_hotel.html","Gis - Collection Hotel","Datamodel information Gis Hotel Technical details Mapped fields Invisible fields Hotel hotel Category: Road Network Name Internal name Size Key? M...",""],
["./example_html/gis_pages/gis_int!brewery_beer.html","Gis - Collection int!brewery_beer","Datamodel information Gis int!brewery_beer Technical details Mapped fields Invisible fields int!brewery_beer int!brewery_beer Category: Expanded j...",""],
["./example_html/gis_pages/gis_int!drawing_pl_of_interes.html","Gis - Collection int!drawing_pl_of_interes","Datamodel information Gis int!drawing_pl_of_interes Technical details Mapped fields Invisible fields int!drawing_pl_of_interes int!drawing_pl_of_i...",""],
["./example_html/gis_pages/gis_int!hetero244855.html","Gis - Collection int!hetero244855","Datamodel information Gis int!hetero244855 Technical details Mapped fields Invisible fields int!hetero244855 int!hetero244855 Category: Expanded j...",""],
["./example_html/gis_pages/gis_int!hetero244932.html","Gis - Collection int!hetero244932","Datamodel information Gis int!hetero244932 Technical details Mapped fields Invisible fields int!hetero244932 int!hetero244932 Category: Expanded j...",""],
["./example_html/gis_pages/gis_int!hetero244956.html","Gis - Collection int!hetero244956","Datamodel information Gis int!hetero244956 Technical details Mapped fields Invisible fields int!hetero244956 int!hetero244956 Category: Expanded j...",""],
["./example_html/gis_pages/gis_int!min_road_pub_rest.html","Gis - Collection int!min_road_pub_rest","Datamodel information Gis int!min_road_pub_rest Technical details Mapped fields Invisible fields int!min_road_pub_rest int!min_road_pub_rest Categ...",""],
["./example_html/gis_pages/gis_int!min_road_road_annotati.html","Gis - Collection int!min_road_road_annotati","Datamodel information Gis int!min_road_road_annotati Technical details Mapped fields Invisible fields int!min_road_road_annotati int!min_road_road...",""],
["./example_html/gis_pages/gis_int!office_drawing.html","Gis - Collection int!office_drawing","Datamodel information Gis int!office_drawing Technical details Mapped fields Invisible fields int!office_drawing int!office_drawing Category: Expa...",""],
["./example_html/gis_pages/gis_int!pub_rest_beer.html","Gis - Collection int!pub_rest_beer","Datamodel information Gis int!pub_rest_beer Technical details Mapped fields Invisible fields int!pub_rest_beer int!pub_rest_beer Category: Expande...",""],
["./example_html/gis_pages/gis_int!road_works_road_works.html","Gis - Collection int!road_works_road_works","Datamodel information Gis int!road_works_road_works Technical details Mapped fields Invisible fields int!road_works_road_works int!road_works_road...",""]];
