hmLoadTopic({
hmKeywords:"",
hmTitle:"Example 2 (Latest version)",
hmDescription:"The following examples are created by the example procs export_camdb() and transform_camdb_xml() defined in the camdb_doc_writer\/source\/procs.magik",
hmPrevLink:"dmdw_example.html",
hmNextLink:"dmdw_your-pages.html",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Example (2)",
hmHeader:"",
hmBody:"<p class=\"p_Normal\">The following examples are created by the example procs <span style=\"font-weight: bold;\">export_camdb() <\/span>and <span style=\"font-weight: bold;\">transform_camdb_xml() <\/span>defined in the <span style=\"font-weight: bold;\">camdb_doc_writer\/source\/procs.magik<\/span><\/p>\n\r<p class=\"p_Normal\">Note that the links to the help will not work.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">As there are multiple datasets are exported, an index page is available:<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><a href=\"example_html\\index.html\" class=\"filelink\">index.html<\/a><\/p><p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">The DMDW xml file is created from the gis database of the Cambridge demonstration database.<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><a href=\"example_html\\gis.xml\" class=\"filelink\">gis.xml<\/a><\/p><p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">This output is based on version 2.0 of the xml writer and the XSLT stylesheet <span style=\"font-weight: bold;\">FileSet3.xsl<\/span>.<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><a href=\"example_html\\gis.html\" class=\"filelink\">gis.html<\/a><\/p><p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
