hmLoadTopic({
hmKeywords:"",
hmTitle:"Meta Data - Global Properties",
hmDescription:"The global properties section contains global DD data from the dataset and information that cannot be extracted from the datamodel, but might help understanding some...",
hmPrevLink:"dmdw_software_version.html",
hmNextLink:"dmdw_default_topology_rules.html",
hmParentLink:"dmdw_xml-content.html",
hmBreadCrumbs:"<a href=\"dmdw_xml-content.html\">XML Content<\/a>",
hmTitlePath:"XML Content > Global Properties",
hmHeader:"",
hmBody:"<p class=\"p_Normal\">The global properties section contains global DD data from the dataset and information that <span style=\"font-style: italic;\">cannot be extracted<\/span> from the datamodel, but might help understanding some properties. They are contained in the element &lt;global_properties&gt;.<\/p>\n\r<p class=\"p_Normal\">These properties are:<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_CodeExample\"><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&lt;<\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #800000;\">global_properties<\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&gt;<\/span><br \/>\n\r<span class=\"f_CodeExample\" style=\"font-weight: bold; color: #000000;\"> &nbsp; &nbsp; <\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&lt;<\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #800000;\">default_topology_rules<\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">\/&gt;<\/span><br \/>\n\r<span class=\"f_CodeExample\" style=\"font-weight: bold; color: #000000;\"> &nbsp; &nbsp; <\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&lt;<\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #800000;\">common_fields<\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">\/&gt;<\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #000000;\"> <\/span><br \/>\n\r<span class=\"f_CodeExample\" style=\"font-weight: bold; color: #000000;\"> &nbsp; &nbsp; <\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&lt;<\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #800000;\">geometry_mappings<\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&gt;<\/span><br \/>\n\r<span class=\"f_CodeExample\" style=\"font-weight: bold; color: #000000;\"> <\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&lt;\/<\/span><span class=\"f_CodeExample\" style=\"font-weight: bold; color: #800000;\">global_properties<\/span><span class=\"f_CodeExample\" style=\"color: #0000ff;\">&gt;<\/span><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
