hmLoadTopic({
hmKeywords:"",
hmTitle:"Pages",
hmDescription:"General information on the pages generated by DMDW.",
hmPrevLink:"dmdw_your-pages.html",
hmNextLink:"dmdw_technical-details.html",
hmParentLink:"dmdw_your-pages.html",
hmBreadCrumbs:"<a href=\"dmdw_your-pages.html\">Your pages<\/a>",
hmTitlePath:"Your pages > Pages",
hmHeader:"",
hmBody:"<p class=\"p_Normal\">General information on the pages generated by DMDW.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
